#YAML 1.0
# terrainGenerator configuration file

version: 1

general:
  verbosity:  1      #verbosity level 0-3

template:
  # filepath:   /home/cappelletto/Desktop/LAD_Test/
  # geoTIFF file that will be used as template. Pixel resolution, NODATA mask, and extent will match the provided one
  filename:   /home/cappelletto/Desktop/LAD_Test/M1_RAW_Bathymetry.tif

output:
  # filepath:   /home/cappelletto/
  filename:   synth_terrain.tif
  format:     tiff  # posible values: tiff, xyz, ply

# Waveform function template:  Y = A.f(B.x + C) + D : amplitude x func(frequency.t + phase) + offset 
parameters:        # Landing AUV parameters
  waveform:  gaussian
  amplitude: 5   # A: Waveform amplitude (peak value)
  frequency: 0.25  # B: Spatial frequency
  phase:     0.0     # C: Spatial phase, also used as t-displacement for Gaussian
  offset:    0.0   # D: Offset
  period:    2.0   # 1/B: reciprocal definition of spatial frequency. Treated as sigma (stdev) for the Gaussian

canvas:
  resolution:     0.01   # [meters] per [pixel]
  rotation:       45      # canvas rotation in degrees (CCW)
  mode:           0      # 0:depth  (positive down) or 1:height (positive up)
  usenodatamask:  true   # indicates if exported geotiff will contain NODATA fields
  nodata:        -9999   # defines default nodata value
  extent:                # canvas limits in meters 
    xmin:         0    
    xmax:         15
    ymin:         0
    ymax:         15
